import runpod
import time
import uuid
import datetime

def handler(event):
    job_id = event.get("id", "unknown")
    now = datetime.datetime.utcnow().isoformat()
    marker = str(uuid.uuid4())[:8]

    print(f"[Hi3DGen] Job received: {job_id}")
    print(f"[Hi3DGen] Marker: {marker}")

    # simulate work
    time.sleep(2)

    return {
        "status": "completed",
        "result": {
            "type": "hi3dgen_test_payload",
            "job_id": job_id,
            "server_time_utc": now,
            "marker": marker,
            "message": "This payload was generated by the RunPod worker",
            "echo_input": event.get("input", {})
        }
    }

if __name__ == "__main__":
    print("Starting Hi3DGen RunPod worker (VISIBLE OUTPUT MODE)")
    runpod.serverless.start({"handler": handler})
